# Generated by Django 2.2.12 on 2021-10-09 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note_date', models.DateTimeField(default=datetime.datetime(2021, 10, 9, 14, 41, 27, 791094, tzinfo=utc), null=True)),
                ('notes', models.TextField()),
            ],
        ),
    ]
